import '@/styles/globals.css';
import '@/styles/markdown.css';
import AppContextProvider from '@/components/AppContext';
import EventBusContextProvide from '@/components/EventBusContext';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
          <EventBusContextProvide>{children}</EventBusContextProvide>
        </AppContextProvider>
      </body>
    </html>
  );
}
